package th.ac.kmitl.science.comsci.example.models.utilities;

public class CountrySubDivisionCodeMapper implements Mapper {

    @Override
    public int map(String dataToMap) throws NotFoundMappingException {

        switch (dataToMap) {
            case "กรุงเทพมหานคร":
                return 1;
            case "กระบี่":
                return 2;
            case "กาญจนบุรี":
                return 3;
            case "กาฬสินธุ์":
                return 4;
            case "กำแพงเพชร":
                return 5;
            case "ขอนแก่น":
                return 6;
            case "จันทบุรี":
                return 7;
            case "ฉะเชิงเทรา":
                return 8;
            case "ชลบุรี":
                return 9;
            case "ชัยนาท":
                return 10;
            case "ชัยภูมิ":
                return 11;
            case "ชุมพร":
                return 12;
            case "เชียงราย":
                return 13;
            case "เชียงใหม่":
                return 14;
            case "ตรัง":
                return 15;
            case "ตราด":
                return 16;
            case "ตาก":
                return 17;
            case "นครนายก":
                return 18;
            case "นครปฐม":
                return 19;
            case "นครพนม":
                return 20;
            case "นครราชสีมา":
                return 21;
            case "นครศรีธรรมราช":
                return 22;
            case "นครสวรรค์":
                return 23;
            case "นนทบุรี":
                return 24;
            case "นราธิวาส":
                return 25;
            case "น่าน":
                return 26;
            case "บึงกาฬ":
                return 27;
            case "บุรีรัมย์":
                return 28;
            case "ปทุมธานี":
                return 29;
            case "ประจวบคีรีขันธ์":
                return 30;
            case "ปราจีนบุรี":
                return 31;
            case "ปัตตานี":
                return 32;
            case "พระนครศรีอยุธยา":
                return 33;
            case "พังงา":
                return 34;
            case "พัทลุง":
                return 35;
            case "พิจิตร":
                return 36;
            case "พิษณุโลก":
                return 37;
            case "เพชรบุรี":
                return 38;
            case "เพชรบูรณ์":
                return 39;
            case "แพร่":
                return 40;
            case "พะเยา":
                return 41;
            case "ภูเก็ต":
                return 42;
            case "มหาสารคาม":
                return 43;
            case "มุกดาหาร":
                return 44;
            case "แม่ฮ่องสอน":
                return 45;
            case "ยะลา":
                return 46;
            case "ยโสธร":
                return 47;
            case "ร้อยเอ็ด":
                return 48;
            case "ระนอง":
                return 49;
            case "ระยอง":
                return 50;
            case "ราชบุรี":
                return 51;
            case "ลพบุรี":
                return 52;
            case "ลำปาง":
                return 53;
            case "ลำพูน":
                return 54;
            case "เลย":
                return 55;
            case "ศรีสะเกษ":
                return 56;
            case "สกลนคร":
                return 57;
            case "สงขลา":
                return 58;
            case "สตูล":
                return 59;
            case "สมุทรปราการ":
                return 60;
            case "สมุทรสงคราม":
                return 61;
            case "สมุทรสาคร":
                return 62;
            case "สระแก้ว":
                return 63;
            case "สระบุรี":
                return 64;
            case "สิงห์บุรี":
                return 65;
            case "สุโขทัย":
                return 66;
            case "สุพรรณบุรี":
                return 67;
            case "สุราษฎร์ธานี":
                return 68;
            case "สุรินทร์":
                return 69;
            case "หนองคาย":
                return 70;
            case "หนองบัวลำภู":
                return 71;
            case "อ่างทอง":
                return 72;
            case "อุดรธานี":
                return 73;
            case "อุทัยธานี":
                return 74;
            case "อุตรดิตถ์":
                return 75;
            case "อุบลราชธานี":
                return 76;
            case "อำนาจเจริญ":
                return 77;
            default:
                throw new NotFoundMappingException("Country Sub Division name not found in CountrySubDivisionCodeMapper.");
        }
    }
}
